<a href="https://colab.research.google.com/github/IgorForceBR0202/linguagens_programacao/blob/main/Atividade_Pratica_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Atividade Prática: Análise de Dados no Varejo com NumPy**

Você acaba de integrar a equipe de dados de uma rede de lojas. Sua primeira missão é analisar o desempenho das vendas e gerar insights de negócios rápidos utilizando o NumPy.


Nível 1: Básico — Faturamento Semanal e Filtros
Sua primeira tarefa envolve analisar o volume de vendas de uma única loja durante uma semana comercial.


In [ ]:
import numpy as np

pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])

print("Peças vendidas:", pecas_vendidas)

Peças vendidas: [150 120  90 210 300 250 180]


In [ ]:
faturamento = pecas_vendidas * 50

print("Faturamento diário:", faturamento)

Faturamento diário: [ 7500  6000  4500 10500 15000 12500  9000]


In [ ]:
mascara = pecas_vendidas > 200

print("Máscara:", mascara)

dias_de_pico = pecas_vendidas[mascara]

print("Vendas nos dias de pico:", dias_de_pico)

Máscara: [False False False  True  True  True False]
Vendas nos dias de pico: [210 300 250]


### **Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema**

Agora você precisa compilar os dados de três filiais diferentes ao longo de quatro dias. A matriz resultante deverá representar as lojas nas linhas e os dias nas colunas.


In [ ]:
import numpy as np

# Passo 1: criar a matriz 2D
vendas = np.array([
    [200, 220, np.nan, 250],  # Loja A
    [150, 180, 160, 190],     # Loja B
    [300, 310, 290, 330]      # Loja C
], dtype=float)

print("Matriz de vendas:")
print(vendas)

# Passo 2: total de peças por loja
totais_lojas = np.nansum(vendas, axis=1)

print("\nTotal de peças por loja:")
print(totais_lojas)

# Passo 3: média diária geral ignorando NaN
media_geral = np.nanmean(vendas)

print("\nMédia diária geral da rede:")
print(media_geral)

# Passo 4: verificar se a meta foi atingida
resultado_meta = np.where(
    vendas >= 200,
    "Meta Atingida",
    "Abaixo"
)

print("\nResultado das metas:")
print(resultado_meta)

# **Atividade Prática: Organização e Transformação de Dados com NumPy**

Esta nova bateria de exercícios simula tarefas reais de preparação de bases de dados e resolução de problemas estruturais.


In [ ]:
import numpy as np

# Passo 1: dias do mês
dias = np.arange(1, 31)
print("Dias do mês:")
print(dias)

# Passo 2: metas de vendas
metas = np.linspace(20000, 30000, 5)
print("\nMetas de vendas:")
print(metas)

# Passo 3: conversão do estoque para inteiros
estoque = np.array([10.5, 20.1, 30.9])
estoque_inteiro = estoque.astype(int)

print("\nEstoque original:")
print(estoque)

print("Estoque convertido:")
print(estoque_inteiro)

# Passo 4: últimos 5 dias em ordem inversa
ultimos_dias_invertidos = dias[-5:][::-1]

print("\nÚltimos 5 dias do mais recente para o mais antigo:")
print(ultimos_dias_invertidos)

### **Nível 2: Intermediário — Redimensionamento e Proteção de Dados**

Aqui, o objetivo é manipular o formato (shape) das matrizes e entender como o Python gerencia a memória durante o fatiamento.


In [ ]:
import numpy as np

# Passo 1 - Array com visitas dos 12 meses
visitas = np.array([
    1200, 1500, 1800,
    2000, 2200, 2500,
    2700, 3000, 3200,
    3500, 3700, 4000
])

# Reorganizando em 4 trimestres x 3 meses
trimestres = visitas.reshape(4, 3)

print("1 - Matriz de trimestres:")
print(trimestres)


# Passo 2 - Dados do primeiro e segundo semestre
primeiro_semestre = np.array([
    [1200, 1500, 1800],
    [2000, 2200, 2500]
])

segundo_semestre = np.array([
    [2700, 3000, 3200],
    [3500, 3700, 4000]
])

# Empilhando verticalmente
dados_completos = np.vstack((primeiro_semestre, segundo_semestre))

print("\n2 - Dados completos:")
print(dados_completos)


# Passo 3 - Extraindo o primeiro trimestre com cópia
primeiro_trimestre = dados_completos[0, :].copy()

print("\n3 - Primeiro trimestre:")
print(primeiro_trimestre)


# Passo 4 - Achatando a matriz
dados_achatados = dados_completos.ravel()

print("\n4 - Dados achatados:")
print(dados_achatados)

1 - Matriz de trimestres:
[[1200 1500 1800]
 [2000 2200 2500]
 [2700 3000 3200]
 [3500 3700 4000]]

2 - Dados completos:
[[1200 1500 1800]
 [2000 2200 2500]
 [2700 3000 3200]
 [3500 3700 4000]]

3 - Primeiro trimestre:
[1200 1500 1800]

4 - Dados achatados:
[1200 1500 1800 2000 2200 2500 2700 3000 3200 3500 3700 4000]
